include:
  - local: "CI/template.yml"

# Any of these variables can be defined in the pipeline, for ease of
# reading only often changed variables are kept here. All variables are
# defined with their default shared across all other pipeline values in ml_pipeline.yml
# Name = Name of child pipeline
# Inputs = Which input configuration to use
# Model = Name of yaml config to use, found in tagger/model/configs
# N_PARAMS = Number of tracking parameters for the track fit
# TRACK_ALGO = Tracking Algorithm, baseline or extended
# TRAIN = Which dataset to use for training
# MINBIAS = Which MinBias to use for rate calculations
# BBBB = Which dataset to use for HH->BBBB efficiency studies
# BBBB_EOS_DIR = Which folder to find the BBBB dataset in
# BBTT = Which dataset to use for BBTauTau efficiency studies
# BBTT_EOS_DIR = Which folder to find the BBTauTau dataset in
# VBFHTAUTAU = Which dataset to use for the VBF->H->TauTau studies
# SIGNAL = Which dataset to use for a specific signal set of ROC curves
# EOS_DATA_DIR = Data directory on eos containing the  above root files
# EOS_DATA_DIR = Where to find the train, minbias, vbfhtautau and signal datasets
# EOS_STORAGE_DIR = Directory to store output products
# EOS_STORAGE_SUBDIR  = Sub Directory for pipeline specific output
# EOS_STORAGE_DATADIR = Sub directory to store branch intermediate training files
# Default false to run a full retraining of a model
# RUN_EMULATION = Switch to turn on the CMSSW emulator, need to have a working CMSSW emualtor for this. Has to run for rerun on tag. Tagged models need FW
# RUN_SYNTHESIS = Switch to turn on the hls4ml and synthesis steps. Emulator needs synthesis to run

DeepSet:baseline_5param_extended_trk:
  extends: .ml_pipeline
  variables:
    Name: ffbinary
    Model: ffbinary
    Train_processes: "MinBias,GGFHHTo4B"
