include:
    - template: Code-Quality.gitlab-ci.yml

stages:
  - data
  - test
  # - train
  # - evaluate

variables:
    EOS_STORAGE_DIR: /eos/user/s/stella/EventTaggerCI/files
    EOS_MODEL_DIR: /eos/user/s/stella/EventTaggerCI/output
    AUTO_DEVOPS_CERNBOX_USER: stella

.template:
  image: gitlab-registry.cern.ch/ml_l1/ops/docker-images/mamba_eventtagger:latest
  before_script:
    - export PYTHONPATH=/builds/ml_l1/EventTaggerCI:$PYTHONPATH
    - echo "$AUTO_DEVOPS_CERNBOX_PASS" | kinit "$AUTO_DEVOPS_CERNBOX_USER@CERN.CH" > /dev/null
    - env
  script:
    - python $FOLDER/$SCRIPT $ARGS
  tags: [cern-nextgen-h100]
  # rules: # run automatically on default branch, tags, and on merge requests with 'ci::automatic-build' label; otherwise run manually
  #    - if: '($CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_LABELS =~ /ci::automatic-build/)'
  #      when: on_success

data:
  extends:
    - .template
  stage: data
  tags: [k8s-gpu]
  variables:
    KUBERNETES_MEMORY_REQUEST: 32Gi
    KUBERNETES_CPU_REQUEST: 2
  # rules:
  #   - changes:  # Include the job and set to when:manual if any of the follow paths match a modified file.
  #       - tagger/data/**
  #     when: manual
  script:
  - source activate eventtagger
  - mkdir files
  - cd files
  - export EOS_MGM_URL=root://eoscms.cern.ch
  - cd ..
  - python tagger/data/make_data.py --signal ${PROCESS}
  - export EOS_MGM_URL=root://eosproject.cern.ch
  - eos mkdir -p ${EOS_STORAGE_DIR}/${PROCESS}
  - eos cp training_data.tgz ${EOS_STORAGE_DIR}/${PROCESS}
  parallel:
    matrix:
      - PROCESS: ["MinBias", "VBFHToBB", "VBFHToTauTau", "VBFHToCC", "GGFHHTo4B", "GGFHHTo2B2Tau"]

# train:
#   extends:
#     - .template
#   stage: train
#   needs:
#     - job : data
#       optional: true
# script:
#   - source activate eventtagger
#   - mkdir -p data
#   - |
#       IFS=',' read -ra PROCS <<< "$Train_processes"

#       for PROC in "${PROCS[@]}"; do
#         echo "Fetching ${PROC}..."
#         eos cp "${EOS_STORAGE_DIR}/${PROC}/training_data.tgz" .
#         mkdir -p "data/${PROC}"
#         tar -xf training_data.tgz -C "data/${PROC}"
#         rm training_data.tgz
#       done

#       # Sort processes so the order in Train_processes does not matter
#       IFS=$'\n' SORTED_PROCS=($(printf '%s\n' "${PROCS[@]}" | sort))

#       PROCESS_SUFFIX=$(IFS='_'; echo "${SORTED_PROCS[*]}")

#       MODEL_SUBDIR="${EOS_MODEL_DIR}/${Name}/${PROCESS_SUFFIX}"

#       echo "Saving model to: ${MODEL_SUBDIR}"

#       python tagger/train/train.py --train --model-config "${Model}.yaml" --model-name "${Name}" --processes "${PROCS[@]}"
#       python tagger/train/train.py --evaluate --model-config "${Model}.yaml" --model-name "${Name}" --processes "${PROCS[@]}"

#       cd "output/${Model}/${PROCESS_SUFFIX}"

#       eos mkdir -p "${MODEL_SUBDIR}"
#       eos cp -r * "${MODEL_SUBDIR}"

#       export MODEL_LOCATION="${MODEL_SUBDIR}"
#   artifacts:
#     paths:
#       - output
#     exclude:
#       - .npy
#     expire_in: 1 day

# evaluate:
#   extends:
#     - .template
#   stage: evaluate
#   tags: [cern-nextgen-h100]
#   script:
#   - eos cp ${EOS_STORAGE_DIR}/${EOS_STORAGE_DATADIR}/training_data_$Inputs.tgz .
#   - tar -xf training_data_$Inputs.tgz
#   - source activate eventtagger
#   - mkdir data
#   - cd data
#   - eos cp $EOS_DATA_DIR/$MINBIAS .
#   - eos cp $BBBB_EOS_DIR/$BBBB .
#   - eos cp $BBTT_EOS_DIR/$BBTT .
#   - eos cp $EOS_DATA_DIR/$VBFHTAUTAU .
#   - cd ..
#   artifacts:
#     paths:
#       - output
#     when: always
#     exclude:
#       - .npy
#     expire_in: 7 days

# code_quality:
#    tags:
#     - docker-privileged-xl
#    artifacts:
#     reports:
#       codequality: gl-code-quality-report.json

# pylint:
#   stage: test
#   image: python:3.7-slim
#   before_script:
#     - mkdir -p public/badges public/lint
#     - echo undefined > public/badges/$CI_JOB_NAME.score
#     - pip install pylint-gitlab
#   script:
#     - pylint --exit-zero --output-format=text $(find -type f -name "*.py" ! -path "**/.venv/**") | tee /tmp/pylint.txt
#     - sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' /tmp/pylint.txt > public/badges/$CI_JOB_NAME.score
#     - pylint --exit-zero --output-format=pylint_gitlab.GitlabCodeClimateReporter $(find -type f -name "*.py" ! -path "**/.venv/**") > codeclimate.json
#     - pylint --exit-zero --output-format=pylint_gitlab.GitlabPagesHtmlReporter $(find -type f -name "*.py" ! -path "**/.venv/**") > public/lint/index.html
#   after_script:
#     - anybadge --overwrite --label $CI_JOB_NAME --value=$(cat public/badges/$CI_JOB_NAME.score) --file=public/badges/$CI_JOB_NAME.svg 4=red 6=orange 8=yellow 10=green
#     - |
#       echo "Your score is: $(cat public/badges/$CI_JOB_NAME.score)"
#   artifacts:
#     paths:
#       - public
#     reports:
#       codequality: codeclimate.json
#     when: always
